(function () {
  const lesson = (page, title, group, engine, summary, fact, visual, source, config = {}) => ({
    id: `page-${page}`,
    page,
    title,
    group,
    engine,
    summary,
    fact,
    visual,
    source,
    config,
  });

  window.TENFOLD_CURRICULUM = [
    lesson(7, "Reading & representing numbers", "Number foundations", "number-sync",
      "Read numbers from left to right, then connect the same number to digits, base-ten blocks, and an abacus.",
      "1,246 = 1 thousand + 2 hundreds + 4 tens + 6 ones",
      "A four-place chart, matching base-ten pieces, and abacus beads stay synchronized.", "Workbook A, p. 4", { number: 1246 }),
    lesson(8, "A digit's place changes its value", "Number foundations", "place-slider",
      "A digit can mean ones, tens, hundreds, or thousands depending on where it sits.",
      "The digit 2 can mean 2, 20, 200, or 2,000.",
      "Move a highlighted 2 through the four place-value columns and watch its block grow.", "Workbook A, p. 10", { digit: 2 }),
    lesson(9, "How many groups are inside?", "Number foundations", "unbundle",
      "Look at a digit and everything to its left to find how many hundreds, tens, or ones a number contains.",
      "1,234 = 1 thousand = 12 hundreds = 123 tens = 1,234 ones",
      "A thousand block can open into hundreds, tens, and ones without changing its value.", "Workbook A, p. 13", { number: 1234 }),
    lesson(10, "Decomposing a number", "Number foundations", "decompose",
      "Break a number into addends that still make the same total.",
      "273 = 200 + 70 + 3",
      "A branching number tree separates hundreds, tens, and ones.", "Workbook A, p. 18", { number: 273 }),
    lesson(11, "Comparing numbers", "Number foundations", "compare",
      "Compare the greatest place first. If it matches, move one place to the right.",
      "346 > 179, but 346 < 379",
      "Two base-ten stacks sit on a balance that tips toward the greater number.", "Workbook A, p. 20", { left: 346, right: 379 }),
    lesson(12, "Symmetry, reflection & friezes", "Geometry", "symmetry",
      "A reflection makes a reverse image the same distance across a line. Repeating reflections create a frieze.",
      "Matching points stay the same distance from the reflection line.",
      "A folding grid mirrors a triangle and repeats it into a continuous strip.", "Workbook A, p. 26"),
    lesson(13, "Addition & addition tables", "Operations", "addition-table",
      "Addition finds a sum. Swapping the terms does not change that sum.",
      "6 + 7 = 13 and 7 + 6 = 13",
      "The selected row and column meet at one highlighted sum in an 11 by 11 table.", "Workbook A, p. 32", { a: 6, b: 7 }),
    lesson(14, "Subtraction & inverse operations", "Operations", "number-line",
      "Subtraction finds a difference and undoes addition. Unlike addition, its terms cannot be reversed.",
      "7 + 9 = 16, so 16 - 9 = 7",
      "A point jumps forward for addition and retraces the same path backward for subtraction.", "Workbook A, p. 34", { start: 7, jump: 9 }),
    lesson(15, "Adding big numbers", "Operations", "column-add",
      "Add ones, tens, hundreds, then thousands. Trade every group of ten for one in the next place.",
      "1,146 + 1,237 = 2,383",
      "Ten ones gather into a tens rod while the written carry appears above the tens column.", "Workbook A, p. 40", { a: 1146, b: 1237, answer: 2383 }),
    lesson(16, "Subtracting big numbers", "Operations", "column-subtract",
      "Subtract one place at a time. When a place is too small, exchange one larger unit for ten smaller units.",
      "2,252 - 1,024 = 1,228",
      "One tens rod opens into ten ones while 5 tens changes to 4 and 2 ones changes to 12.", "Workbook A, p. 43", { a: 2252, b: 1024, answer: 1228 }),
    lesson(17, "Cartesian planes", "Geometry", "coordinate",
      "Locate a point with an ordered pair: horizontal position first, vertical position second.",
      "Point A = (5, 2)",
      "Dashed guides meet at a draggable point on a grid from 0 through 7.", "Workbook A, p. 50", { x: 5, y: 2 }),
    lesson(18, "Finding missing terms", "Operations", "missing-term",
      "Use the inverse operation to discover the number that makes both sides equal.",
      "□ + 39 = 69, so 69 - 39 = 30",
      "An equation flow reveals the inverse step, then checks the missing value.", "Workbook A, p. 56", { problems: ["□ + 39 = 69", "58 + □ = 72", "□ - 22 = 57", "49 - □ = 25"] }),
    lesson(19, "Angles & line relationships", "Geometry", "angle",
      "Two lines meeting at a vertex make an angle. Lines can also be parallel or perpendicular.",
      "Acute < 90°, right = 90°, obtuse > 90°",
      "A virtual paper corner compares with an adjustable angle; line pairs change below it.", "Workbook A, p. 72", { angle: 90 }),
    lesson(20, "Polygons", "Geometry", "polygon",
      "A polygon is a closed figure made from straight lines. Classify it by sides and by whether it points inward.",
      "Triangle = 3 sides; quadrilateral = 4 sides",
      "Four crisp polygons can be sorted as triangle, quadrilateral, convex, or nonconvex.", "Workbook A, p. 78"),
    lesson(21, "Estimating collections", "Measurement & data", "estimate",
      "Count a sample, decide how many equal samples fit, then multiply to estimate the whole collection.",
      "4 samples of about 50 gemstones ≈ 200 gemstones",
      "A movable sample window highlights one quarter of a four-part gemstone field.", "Workbook A, p. 84", { sample: 50, groups: 4 }),
    lesson(22, "Counting large collections", "Number foundations", "bundle",
      "Organize large quantities into hundreds, tens, and ones so the total is easy to read.",
      "7 × 100 + 4 × 10 + 3 = 743",
      "Loose coins bundle into sacks of ten, then ten sacks become a chest of one hundred.", "Workbook A, p. 86", { number: 743 }),
    lesson(23, "The meaning of multiplication", "Multiplication & division", "array",
      "Multiplication finds a product from equal rows and columns. Rotating an array swaps the factors but keeps the product.",
      "2 × 4 = 8 and 4 × 2 = 8",
      "A counter array rotates between rows and columns while the equation updates.", "Workbook A, p. 92", { rows: 2, cols: 4 }),
    lesson(24, "The meaning of division", "Multiplication & division", "division",
      "Division shares a quantity into equal groups or asks how many times one number fits inside another.",
      "18 ÷ 3 = 6; division by zero is impossible",
      "Eighteen counters distribute evenly into three visible boxes.", "Workbook A, p. 94", { total: 18, groups: 3 }),
    lesson(25, "Fractions", "Fractions & decimals", "fraction",
      "A fraction names equal parts of one whole or of a collection. The numerator is considered; the denominator is the total.",
      "1/4 is one of four equal parts; 2/3 is two of three equal parts.",
      "A circular whole and a matching collection shade the same chosen fraction.", "Workbook A, p. 100", { numerator: 1, denominator: 4 }),
    lesson(26, "Comparing fractions", "Fractions & decimals", "fraction-compare",
      "When identical wholes have the same denominator, compare their numerators.",
      "1/4 < 2/4",
      "Two equal-length fraction bars make the shaded amounts directly comparable.", "Workbook A, p. 105", { denominator: 4, left: 1, right: 2 }),
    lesson(27, "Decimal numbers", "Fractions & decimals", "decimal-place",
      "The decimal point separates the whole part from tenths and hundredths.",
      "231.11 = 2 hundreds + 3 tens + 1 one + 1 tenth + 1 hundredth",
      "A place-value magnifier travels from a hundred block down to a hundredth piece.", "Workbook A, p. 110", { value: "231.11" }),
    lesson(28, "Coins & decimal numbers", "Fractions & decimals", "money",
      "Money uses hundredths. Always write two digits for cents.",
      "$1.45 = $1 + 4 × $0.10 + $0.05; write $3.40, not $3.4",
      "Dollar, ten-cent, and five-cent pieces land in matching decimal columns.", "Workbook A, p. 113", { target: 1.45 }),
    lesson(29, "Metric length", "Measurement & data", "metric",
      "Convert metres, decimetres, centimetres, and millimetres by moving the decimal point to the target unit.",
      "1 m = 10 dm = 100 cm = 1,000 mm",
      "One highlighted decimal marker slides across m, dm, cm, and mm columns.", "Workbook B, p. 4", { value: 124, unit: "cm" }),
    lesson(30, "Perimeter", "Measurement & data", "perimeter",
      "Perimeter is the total length around the outside of a plane figure.",
      "4 + 2 + 4 + 2 = 12 cm",
      "A bright tracing dot travels around an adjustable rectangle while each side is counted.", "Workbook B, p. 8", { width: 4, height: 2 }),
    lesson(31, "Tables & bar graphs", "Measurement & data", "bar-graph",
      "Tables organize data in rows and columns. Bar graphs show the same data with equal-width bars and ordered axes.",
      "Cats = 5, Dogs = 2, Fish = 8",
      "A switch transforms the pet-shop table into three animated bars without changing the data.", "Workbook B, p. 12", { values: [5, 2, 8] }),
    lesson(32, "Prisms & pyramids", "Geometry", "solid",
      "Prisms have two identical parallel bases. Pyramids have one base and triangular faces meeting at one vertex.",
      "Prism = 2 bases; pyramid = 1 base + 1 apex",
      "A rotatable solid highlights its base, faces, edges, and vertices one feature at a time.", "Workbook B, p. 18"),
    lesson(33, "Nets of solids", "Geometry", "net",
      "A net lays every face of a solid flat. Folding those faces recreates the solid.",
      "Triangular prism net = 2 triangles + 3 rectangles; triangular pyramid net = 4 triangles",
      "A flat net folds in three stages, keeping every face visible and counted.", "Workbook B, p. 21"),
    lesson(34, "Multiplication tables", "Multiplication & division", "multiplication-table",
      "A multiplication table finds the product where a factor's row meets the other factor's column.",
      "3 × 4 = 12",
      "An 11 by 11 grid highlights both factors and expands the selected cell into an array.", "Workbook B, p. 24", { a: 3, b: 4 }),
    lesson(35, "Division & area", "Multiplication & division", "area",
      "Division and multiplication describe equal groups. Area counts the square units covering a closed surface.",
      "16 ÷ 8 = 2 ↔ 2 × 8 = 16; a 2 × 3 rectangle has area 6",
      "Tap square units on a grid; the related multiplication and division facts update together.", "Workbook B, pp. 28 & 34", { rows: 2, cols: 3 }),
    lesson(36, "Equivalent fractions", "Fractions & decimals", "equivalent-fractions",
      "Equivalent fractions divide equal wholes differently but shade the same amount.",
      "1/3 = 2/6 = 4/12",
      "Three stacked fraction strips keep identical length while their partitions change.", "Workbook B, p. 40", { sets: [[1, 3], [2, 6], [4, 12]] }),
    lesson(37, "Adding & subtracting decimals", "Fractions & decimals", "decimal-operation",
      "Line up place values and decimal points, add zeroes when helpful, then bring the decimal point straight into the result.",
      "2.32 + 4.86 = 7.18; 4.31 - 2.19 = 2.12",
      "Decimal cards snap into aligned ones, tenths, and hundredths columns before calculation begins.", "Workbook B, pp. 58 & 60"),
    lesson(38, "Two-digit multiplication", "Multiplication & division", "partial-products",
      "Split a two-digit factor into tens and ones, multiply each part, then add the partial products.",
      "4 × 23 = 4 × 20 + 4 × 3 = 80 + 12 = 92",
      "An area box separates 23 into 20 and 3, then fills both partial products.", "Workbook B, p. 68", { factor: 4, value: 23 }),
    lesson(39, "Rounding natural numbers", "Number foundations", "rounding",
      "Rounding replaces a number with the closest ten, hundred, or thousand. An exact midpoint rounds up.",
      "583 → 580; 1,234 → 1,200; 13,500 → 14,000",
      "A movable number sits between two endpoints and rolls toward the nearer one.", "Workbook B, p. 74", { value: 583, place: 10 }),
    lesson(40, "Even & odd numbers", "Patterns & properties", "pairing",
      "Even numbers make complete pairs. Odd numbers leave exactly one object without a partner.",
      "Even endings: 0, 2, 4, 6, 8; odd endings: 1, 3, 5, 7, 9",
      "Counters click into pairs while any remainder stays visibly alone.", "Workbook B, p. 80", { number: 16 }),
    lesson(41, "Prime & composite numbers", "Patterns & properties", "factors",
      "Composite numbers form equal groups in more than one way. Prime numbers do not. Zero and one are neither.",
      "9 = 3 × 3 is composite; 7 is prime",
      "Counters try every rectangular arrangement and record which ones fit without a remainder.", "Workbook B, p. 82", { number: 9 }),
    lesson(42, "Number patterns", "Patterns & properties", "pattern",
      "A number pattern follows a rule that tells what comes next.",
      "15, 25, 35… uses +10; 2, 4, 8, 16… uses ×2",
      "Blocks travel through a rule machine and the learner supplies the next output.", "Workbook B, p. 86"),
    lesson(43, "Time & telling time", "Measurement & data", "clock",
      "The short hand shows hours, the long hand shows minutes, and the thin hand shows seconds.",
      "1 hour = 60 minutes; 1 minute = 60 seconds",
      "Adjustable clock hands stay synchronized with a digital time display.", "Workbook B, p. 92", { hour: 10, minute: 20, second: 5 }),
    lesson(44, "Volume, capacity & mass", "Measurement & data", "measure-sort",
      "Volume is space occupied, capacity is what a container can hold, and mass is the amount of matter.",
      "Car vs motorcycle: volume; jug vs glass: capacity; adult vs child: mass",
      "Three comparison scenes sort beneath the correct property and explain why.", "Workbook B, p. 96"),
    lesson(45, "Probability", "Measurement & data", "probability",
      "Probability describes how likely an outcome is: impossible, possible, or certain.",
      "Likelihood runs from impossible (0) to certain (1).",
      "Change the marbles in a bag, make repeated draws, and compare predictions with results.", "Workbook B, p. 100", { red: 2, blue: 3 }),
    lesson(46, "Combinations", "Measurement & data", "combinations",
      "A combination table organizes every possible outcome from two sets of choices.",
      "3 animals × 4 nuts = 12 combinations",
      "A growing 3 by 4 grid pairs each animal with each nut exactly once.", "Workbook B, p. 103"),
    lesson(47, "Equivalent expressions", "Patterns & properties", "expressions",
      "Different operations are equivalent when they produce the same result.",
      "15 + 10 = 20 + 5 = 5 × 5 = 25 + 0 = 30 - 5 = 25",
      "Expression tiles connect to one target only when their values match.", "Workbook B, p. 108", { target: 25 }),
    lesson(48, "Scratchpad", "Tools", "scratchpad",
      "Use the book's blue-grid transition page as a free space for sketches, arrays, number lines, and working.",
      "Your marks stay on this device until you clear them.",
      "A touch-friendly blue graph canvas supports drawing and erasing.", "Section break / notes page"),
    lesson(49, "The effect of zero", "Mental math", "mental",
      "Adding or subtracting zero leaves a number unchanged. Subtracting a number from itself makes zero.",
      "N + 0 = N; N - 0 = N; N - N = 0",
      "A four-column fact family changes together as the chosen number changes.", "Mental arithmetic, p. 49", { strategy: "zero", n: 5 }),
    lesson(50, "One more, one less", "Mental math", "mental",
      "Move to the neighboring number to add or subtract one.",
      "N + 1; 1 + N; N - 1; (N + 1) - N = 1",
      "One counter steps on or off a number track while the related facts update.", "Mental arithmetic, p. 50", { strategy: "one", n: 4 }),
    lesson(51, "Two more, two fewer", "Mental math", "mental",
      "Skip-count two spaces forward or backward.",
      "N + 2; 2 + N; (N + 2) - 2 = N",
      "A pair of counters hops together along a number track.", "Mental arithmetic, p. 51", { strategy: "two", n: 3 }),
    lesson(52, "Doubles", "Mental math", "mental",
      "A double adds the same number twice; the related subtraction splits the total in half.",
      "N + N = 2N; 2N - N = N",
      "One counter row mirrors into an identical second row.", "Mental arithmetic, p. 52", { strategy: "double", n: 7 }),
    lesson(53, "Doubles plus or minus one", "Mental math", "mental",
      "Use a known double, then adjust by one for neighboring addends.",
      "N + (N + 1) = N + N + 1",
      "Two nearly equal rows align; the single extra counter stays highlighted.", "Mental arithmetic, p. 53", { strategy: "near-one", n: 6 }),
    lesson(54, "Doubles plus or minus two", "Mental math", "mental",
      "Use a known double, then adjust by two when the addends differ by two.",
      "N + (N + 2) = N + N + 2",
      "Two extra counters slide out from the second equal row.", "Mental arithmetic, p. 54", { strategy: "near-two", n: 6 }),
    lesson(55, "Ten more, ten fewer", "Mental math", "mental",
      "Adding or subtracting ten changes the tens place while the ones place stays put.",
      "4 + 10 = 14; 14 - 10 = 4",
      "One tens rod enters or leaves while the ones remain anchored.", "Mental arithmetic, p. 55", { strategy: "ten", n: 4 }),
    lesson(56, "Make ten with nine", "Mental math", "make-ten",
      "Move one from the second addend to nine, make ten, then add what remains.",
      "9 + 5 = (9 + 1) + 4 = 14",
      "One counter snaps into the final opening of a ten-frame before leftovers are counted.", "Mental arithmetic, p. 56", { base: 9, add: 5 }),
    lesson(57, "Make ten with eight", "Mental math", "make-ten",
      "Move two from the second addend to eight, make ten, then add what remains.",
      "8 + 7 = (8 + 2) + 5 = 15",
      "Two counters snap into the final openings of a ten-frame before leftovers are counted.", "Mental arithmetic, p. 57", { base: 8, add: 7 }),
    lesson(58, "Grouping several addends", "Mental math", "grouping",
      "Look for friendly pairs that make ten before adding the remaining terms.",
      "a + b + c = (a + b) + c",
      "Three number tiles can be reordered; a magnetic bracket joins the friendly pair.", "Mental arithmetic, p. 58", { values: [7, 3, 6] }),
    lesson(59, "Master addition table", "Mental math", "addition-table",
      "The full addition table gathers every sum from zero through ten. Strategy shading shows facts you already know.",
      "0 + 0 = 0 through 10 + 10 = 20",
      "Rows and columns highlight on touch; familiar strategy zones are softly shaded.", "Mental arithmetic, p. 59", { a: 8, b: 7, mastery: true }),
    lesson(60, "Ready for multiplication & division", "Tools", "transition",
      "This blue-grid transition marks the end of the available source extraction and the start of the next mental-math chapter.",
      "Pages 61-73 need their source material before they can be represented faithfully.",
      "A calm blue grid shows completed concepts and the clearly labeled remaining source gap.", "Section transition, p. 60"),
  ];
})();
